apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: abdallahelarabyhelm
spec:
  type: LoadBalancer
  {{- if .Values.labelsenable }}
  selector:
    app: {{.Values.mylabel}}
  {{- end }}
  ports:
  - port: 5000
    targetPort: 5000
